
[functions.oauth-cb]
enabled = true
verify_jwt = true
import_map = "./functions/oauth-cb/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/oauth-cb/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/oauth-cb/*.html" ]

[functions.calendar-list]
enabled = true
verify_jwt = true
import_map = "./functions/calendar-list/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calendar-list/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calendar-list/*.html" ]

[functions.sync-captures]
enabled = true
verify_jwt = true
import_map = "./functions/deno.json"
entrypoint = "./functions/sync-captures/index.ts"
